const inputs= {
  age_in_years: '1',
  arrested_dui: 'yes',
  bicycle_helmet_usage: '',
  binge_drinking: 'yes',
  blood_glucose_mml: '4',
  blood_glucose: '4',
  blood_pressure_estimated: 'not_answered',
  blood_pressure_measured_high_number: '1',
  blood_pressure_measured_low_number: '1',
  blood_pressure_medication: '1',
  body_frame_size: 'not_answered',
  butter: 'not answered',
  caffeine: 'yes',
  charcoal_broiled: 'yes',
  chh_cough: 'not answered',
  chh_fever: 'not answered',
  chh_hands: 'not_answered',
  chh_interact: 'not answered',
  chh_sbreath: 'not answered',
  cholesterol_check: 'not_answered',
  cholesterol_level_estimated: 'not_answered',
  cholesterol_level_mml: '1',
  cholesterol_level: '1',
  cholesterol_medication: '1',
  colon_cancer_screening: '',
  commercial_driver: 'yes',
  cross_contamination: 'yes',
  daily_cigars: '2',
  daily_marajuana: '2',
  daily_pipes: '2',
  daily_shisha: '2',
  desserts: 'not answered',
  diabetes_status: 'yes',
  difficulties_piling_up: '',
  distracted_driving: 'yes',
  drinking_and_driving: '23',
  driving_speed: 'do not drive',
  education: '',
  fast_food: 'not answered',
  felt_confident: '',
  filling_forms: '',
  fish: 'yes',
  fruit: 'not answered',
  fruits_and_vegetables: 'yes',
  GADa: '',
  GADb: '',
  GADc: '',
  GADd: '',
  GADe: '',
  GADf: '',
  GADg: '',
  gainful_employment: '',
  going_your_way: '',
  gross_weight: 'yes',
  hb1ac_check: '',
  hdl_cholesterol_estimated: 'not_answered',
  hdl_cholesterol_mml: '4',
  hdl_cholesterol: '4',
  health_information_interest: '',
  heart_attack: 'yes',
  heart_disease: 'yes',
  height_cm: '2',
  height_feet: '1',
  height_inches: '2',
  height: '',
  helmet_usage: '',
  high_cholesterol_food: 'yes',
  hispanic_origin: '',
  home_safety: '',
  household_income: '',
  hysterectomy: '',
  insurance_coverage: '',
  junk_food: 'not answered',
  last_mammogram: '',
  marital_status: '',
  misfortune: '',
  overall_health: '',
  pap_smear_test: '',
  PHQa: '',
  PHQb: '',
  PHQc: '',
  PHQd: '',
  PHQe: '',
  PHQf: '',
  PHQg: '',
  PHQh: '',
  PHQi: '',
  protein: 'not answered',
  race: '',
  readiness_to_eat_healthier: '',
  readiness_to_exercise_more: '',
  readiness_to_quit_smoking: '',
  readiness_to_reduce_alcohol_usage: '',
  resting_heart_rate: '',
  road_rage: 'yes',
  safety_belt_usage: '4',
  save_key: '',
  sex: 'not_answered',
  sleep1: 'not answered',
  sleep2: 'not answered',
  sleep3: 'not answered',
  sleep4: 'not answered',
  smokeless_tobacco: '3',
  smoking: 'never_smoked',
  soft_drinks: 'not answered',
  stage: '',
  state_of_residence: '',
  still_smoke: '1',
  stroke: 'yes',
  sugar_beverage: 'yes',
  travel_by_automobile_km: '22',
  travel_by_automobile: '22',
  travel_by_motorcycle_km: '22',
  travel_by_motorcycle: '22',
  triglycerides: '4',
  type_of_license: 'a',
  typical_travel_method: 'not_answered',
  unable_to_control: '',
  used_to_smoke_cigarettes_day: '1',
  used_to_smoke_cigars_day: '1',
  used_to_smoke_pipes_day: '1',
  vaping_freq: '1-2 days',
  vaping: 'yes',
  vegetables: 'not answered',
  weekly_alcohol_beer: '40',
  weekly_alcohol_mixed_drinks: '54',
  weekly_alcohol_wine_coolers: '45',
  weekly_alcohol_wine: '90',
  weekly_physical_activity: '',
  weight_kg: '2',
  weight: '1',
  years_as_driver: '4',
  years_since_quitting_months: '4',
  years_since_quitting_years: '4',
}

const json = `{"appraise_risks.client_id":"${process.env.NODE_ENV === 'production' ? process.env.GHM_CLIENT_FINAL : process.env.GHM_CLIENT}","appraise_risks.user_id":"${req.userId}","appraise_risks.company":"${req.user.company}","hra.app.units":"metric","hra.app.cholunits":"mg/dl","hra.app.hra_id":"midlife","save_key":"${req.userId}", "hra.q.sex.a": "${currentResponse.sex}", "hra.q.age_in_years.a.years": "${currentResponse.age_in_years}", "hra.q.height_cm.a.centimeters": "${currentResponse.height_cm}", "hra.q.weight_kg.a.kilograms": "${currentResponse.weight_kg}", "hra.q.cholesterol_check.a": "${currentResponse.cholesterol_check || 'not answered'}","hra.q.gross_weight.a": "${currentResponse.gross_weight || 'not answered'}", "hra.q.body_frame_size.a": "${currentResponse.body_frame_size || 'not answered'}", "hra.q.diabetes_status.a": "${currentResponse.diabetes_status || 'not answered'}", "hra.q.stroke.a": "${currentResponse.stroke || 'not answered'}", "hra.q.heart_attack.a": "${currentResponse.heart_attack || 'not answered'}", "hra.q.heart_disease.a": "${currentResponse.heart_disease || 'not answered'}", "hra.q.blood_pressure_medication.a": "${currentResponse.blood_pressure_medication || 'not answered'}", "hra.q.blood_pressure_measured.a.high_number": "${currentResponse.blood_pressure_measured_high_number || 'not answered'}", "hra.q.blood_pressure_measured.a.low_number": "${currentResponse.blood_pressure_measured_low_number || 'not answered'}", "hra.q.blood_pressure_estimated.a": "${currentResponse.blood_pressure_estimated || 'not answered'}", "hra.q.cholesterol_level.a.mg_dl": "${currentResponse.cholesterol_level || 'not answered'}", "hra.q.cholesterol_level_mml.a": "${currentResponse.cholesterol_level_mml || 'not answered'}", "hra.q.cholesterol_level_estimated.a": "${currentResponse.cholesterol_level_estimated || 'not answered'}", "hra.q.hdl_cholesterol_estimated.a": "${currentResponse.hdl_cholesterol_estimated || 'not answered'}", "hra.q.hdl_cholesterol_mml.a": "${currentResponse.hdl_cholesterol_mml || 'not answered'}", "hra.q.hdl_cholesterol.a.mg_dl": "${currentResponse.hdl_cholesterol || 'not answered'}", "hra.q.smoking.a": "${currentResponse.smoking || 'not answered'}", "hra.q.used_to_smoke.a.cigarettes_day": "${currentResponse.used_to_smoke || 'not answered'}", "hra.q.used_to_smoke.a.cigars_day": "${currentResponse.used_to_smoke || 'not answered'}", "hra.q.used_to_smoke.a.pipes_day": "${currentResponse.used_to_smoke || 'not answered'}", "hra.q.years_since_quitting.a.years": "${currentResponse.years_since_quitting_years || 'not answered'}", "hra.q.years_since_quitting.a.months": "${currentResponse.years_since_quitting_months || 'not answered'}", "hra.q.still_smoke.a.cigarettes_day": "${currentResponse.still_smoke || 'not answered'}", "hra.q.daily_cigars.a": "${currentResponse.daily_cigars || 'not answered'}", "hra.q.daily_pipes.a": "${currentResponse.daily_pipes || 'not answered'}", "hra.q.daily_marajuana.a": "${currentResponse.daily_marijuana || 'not answered'}", "hra.q.daily_shisha.a": "${currentResponse.daily_shisha || 'not answered'}", "hra.q.cross_daily_cigars.a": "${currentResponse.cross_daily_cigars || 'not answered'}", "hra.q.cross_daily_marijuana.a": "${currentResponse.cross_daily_marijuana || 'not answered'}", "hra.q.cross_daily_pipes.a": "${currentResponse.cross_daily_pipes || 'not answered'}", "hra.q.cross_daily_shisha.a": "${currentResponse.cross_daily_shisha || 'not answered'}", "hra.q.smokeless_tobacco.a.times_day": "${currentResponse.smokeless_tobacco || 'not answered'}", "hra.q.typical_travel_method.a": "${currentResponse.typical_travel_method || 'not answered'}", "hra.q.safety_belt_usage.a.%": "${currentResponse.safety_belt_usage || 'not answered'}", "hra.q.distracted_driving.a": "${currentResponse.distracted_driving || 'not answered'}", "hra.q.driving_speed.a": "${currentResponse.driving_speed || 'not answered'}", "hra.q.drinking_and_driving.a.times_last_month": "${currentResponse.drinking_and_driving || 'not answered'}", "hra.q.weekly_alcohol.a.beer": "${currentResponse.weekly_alcohol_beer || 'not answered'}", "hra.q.weekly_alcohol.a.wine": "${currentResponse.weekly_alcohol_wine || 'not answered'}", "hra.q.weekly_alcohol.a.wine_coolers": "${currentResponse.weekly_alcohol_wine_coolers || 'not answered'}", "hra.q.weekly_alcohol.a.mixed_drinks": "${currentResponse.weekly_alcohol_mixed_drinks || 'not answered'}", "hra.q.binge_drinking.a": "${currentResponse.binge_drinking || 'not answered'}", "hra.q.a.age_at_menarche.a.years_old": "${currentResponse.age_at_menarche ||'not answered'}", "hra.q.age_at_bearing_first_child.a.years_old": "${currentResponse.age_of_bearing_first_child}", "hra.q.last_mammogram.a": "${currentResponse.last_mammogram || 'not answered'}", "hra.q.family_breast_cancer_history.a.women": "${currentResponse.family_breast_cancer_history || 'not answered'}", "hra.q.hysterectomy.a": "${currentResponse.hysterectomy || 'not answered'}", "hra.q.pap_smear_test.a": "${currentResponse.pap_smear_test || 'not answered'}", "hra.q.colon_cancer_screening.a": "${currentResponse.colon_cancer_screening || 'not answered'}", "hra.q.fast_food.a": "${currentResponse.fast_food || 'not answered'}", "hra.q.fruit.a": "${currentResponse.fruit || 'not answered'}", "hra.q.vegetables.a": "${currentResponse.vegetables || 'not answered'}", "hra.q.fruits_and_vegetables.a": "${currentResponse.fruits_and_vegetables || 'not answered'}", "hra.q.soft_drinks.a": "${currentResponse.soft_drinks || 'not answered'}", "hra.q.protein.a": "${currentResponse.protein || 'not answered'}", "hra.q.junk_food.a": "${currentResponse.junk_food || 'not answered'}", "hra.q.desserts.a": "${currentResponse.desserts || 'not answered'}", "hra.q.butter.a": "${currentResponse.butter || 'not answered'}", "hra.q.sleep1.a": "${currentResponse.sleep1 || 'not answered'}", "hra.q.sleep2.a": "${currentResponse.sleep2 || 'not answered'}", "hra.q.sleep3.a": "${currentResponse.sleep3 || 'not answered'}", "hra.q.sleep4.a": "${currentResponse.sleep4 || 'not answered'}", "hra.q.PHQa.a": "${currentResponse.PHQa || 'not answered'}", "hra.q.PHQb.a": "${currentResponse.PHQb || 'not answered'}", "hra.q.PHQc.a": "${currentResponse.PHQc || 'not answered'}", "hra.q.PHQd.a": "${currentResponse.PHQd || 'not answered'}", "hra.q.PHQe.a": "${currentResponse.PHQe || 'not answered'}", "hra.q.PHQf.a": "${currentResponse.PHQf || 'not answered'}", "hra.q.PHQg.a": "${currentResponse.PHQg || 'not answered'}", "hra.q.PHQh.a": "${currentResponse.PHQh || 'not answered'}", "hra.q.PHQi.a": "${currentResponse.PHQi || 'not answered'}", "hra.q.GADa.a": "${currentResponse.GADa || 'not answered'}", "hra.q.GADb.a": "${currentResponse.GADb || 'not answered'}", "hra.q.GADc.a": "${currentResponse.GADc || 'not answered'}", "hra.q.GADd.a": "${currentResponse.GADd || 'not answered'}", "hra.q.GADe.a": "${currentResponse.GADe || 'not answered'}", "hra.q.GADf.a": "${currentResponse.GADf || 'not answered'}", "hra.q.GADg.a": "${currentResponse.GADg || 'not answered'}", "hra.q.unable_to_control.a": "${currentResponse.unable_to_control || 'not answered'}", "hra.q.felt_confident.a": "${currentResponse.felt_confident || 'not answered'}", "hra.q.going_your_way.a": "${currentResponse.going_your_way || 'not answered'}", "hra.q.difficulties_piling_up.a": "${currentResponse.difficulties_piling_up || 'not answered'}", "hra.q.home_safety.a": "${currentResponse.home_safety || 'not answered'}", "hra.q.overall_health.a": "${currentResponse.overall_health || 'not answered'}", "hra.q.weekly_physical_activity.a": "${currentResponse.weekly_physical_activity || 'not answered'}", "hra.q.helmet_usage.a": "${currentResponse.helmet_usage || 'not answered'}", "hra.q.bicycle_helmet_usage.a": "${currentResponse.bicycle_helmet_usage || 'not answered'}", "hra.q.resting_heart_rate.a.bpm": "${currentResponse.resting_heart_rate || 'not answered'}", "hra.q.readiness_to_quit_smoking.a": "${currentResponse.readiness_to_quit_smoking || 'not answered'}", "hra.q.readiness_to_reduce_alcohol_usage.a": "${currentResponse.readiness_to_reduce_alcohol_usage || 'not answered'}", "hra.q.readiness_to_eat_healthier.a": "${currentResponse.readiness_to_eat_healthier || 'not answered'}", "hra.q.readiness_to_exercise_more.a": "${currentResponse.readiness_to_exercise_more || 'not answered'}", "hra.q.misfortune.a": "${currentResponse.misfortune || 'not answered'}", "hra.q.race.a": "${currentResponse.race || 'not answered'}", "hra.q.hispanic_origin.a": "${currentResponse.hispanic_origin || 'not answered'}", "hra.q.filling_forms.a": "${currentResponse.filling_forms || 'not answered'}", "hra.q.education.a": "${currentResponse.education || 'not answered'}", "hra.q.state_of_residence.a": "${currentResponse.state_of_residence || 'not answered'}", "hra.q.marital_status.a": "${currentResponse.marital_status || 'not answered'}", "hra.q.household_income.a": "${currentResponse.household_income || 'not answered'}", "hra.q.gainful_employment.a": "${currentResponse.gainful_employment || 'not answered'}", "hra.q.insurance_coverage.a": "${currentResponse.insurance_coverage || 'not answered'}", "hra.q.health_information_interest.a": "${currentResponse.health_information_interest || 'not answered'}","hra.q.arrested_dui.a.years": "${currentResponse.arrested_dui || 'not answered'}", "hra.q.blood_glucose.a": "${currentResponse.blood_glucose || 'not answered'}", "hra.q.blood_glucose_mml.a": "${currentResponse.blood_glucose_mml || 'not answered'}", "hra.q.charcoal_broiled.a": "${currentResponse.charcoal_broiled || 'not answered'}", "hra.q.chh_cough.a": "${currentResponse.chh_cough || 'not answered'}", "hra.q.chh_fever.a": "${currentResponse.chh_fever || 'not answered'}", "hra.q.chh_hands.a": "${currentResponse.chh_hands || 'not answered'}", "hra.q.chh_interact.a": "${currentResponse.chh_interact || 'not answered'}", "hra.q.chh_sbreath.a": "${currentResponse.chh_sbreath || 'not answered'}", "hra.q.commercial_driver.a": "${currentResponse.commercial_driver || 'not answered'}", "hra.q.cross_contamination.a": "${currentResponse.cross_contamination || 'not answered'}", "hra.q.hb1ac_check.a": "${currentResponse.hb1ac_check || 'not answered'}", "hra.q.sugar_beverage.a": "${currentResponse.sugar_beverage || 'not answered'}", "hra.q.triglycerides.a": "${currentResponse.triglycerides || 'not answered'}", "hra.q.type_of_license.a": "${currentResponse.type_of_license || 'not answered'}", "hra.q.vaping.a": "${currentResponse.vaping || 'not answered'}", "hra.q.years_as_driver.a": "${currentResponse.years_as_driver ||'not answered'}", "hra.q.years_since_quitting_months.a": "${currentResponse.years_since_quitting_months ||'not answered'}", "hra.q.years_since_quitting_years.a": "${currentResponse.years_since_quitting_years || 'not answered'}", "hra.q.caffeine.a": "${currentResponse.caffeine || 'not answered'}", "hra.q.fish.a": "${currentResponse.fish || 'not answered'}", "hra.q.bathing.a": "${currentResponse.bathing || 'not answered'}", "hra.q.dressing.a": "${currentResponse.dressing ||'not answered'}", "hra.q.eating.a": "${currentResponse.eating || 'not answered'}", "hra.q.heavy_housework.a": "${currentResponse.heavy_housework || 'not answered'}", "hra.q.light_housework.a": "${currentResponse.light_housework || 'not answered'}", "hra.q.out_of_house.a": "${currentResponse.out_of_house ||'not answered'}", "hra.q.out_of_bed.a": "${currentResponse.out_of_bed || 'not answered'}", "hra.q.walking.a": "${currentResponse.walking || 'not answered'}", "hra.q.getting_outside.a": "${currentResponse.getting_outside ||'not answered'}", "hra.q.using_toilet.a": "${currentResponse.using_toilet ||'not answered'}", "hra.q.meals.a": "${currentResponse.meals ||'not answered'}", "hra.q.shopping.a": "${currentResponse.shopping ||'not answered'}", "hra.q.managing_money.a": "${currentResponse.managing_money ||'not answered'}", "hra.q.telephone.a": "${currentResponse.telephone || 'not answered'}", "hra.q.limit_crime.a": "${currentResponse.limit_crime ||'not answered'}", "hra.q.prostate_cancer_screening.a": "${currentResponse.prostate_cancer_screening ||'not answered'}", "hra.q.relatives_cancer.a": "${currentResponse.relatives_cancer ||'not answered'}", "hra.q.unprotected_sex.a": "${currentResponse.unprotected_sex ||'not answered'}", "hra.q.street_drugs.a": "${currentResponse.street_drugs ||'not answered'}"}`;