const inputs= {
  age_in_years: '1',
  arrested_dui: 'yes',
  bicycle_helmet_usage: '',
  binge_drinking: 'yes',
  blood_glucose_mml: '4',
  blood_glucose: '4',
  blood_pressure_estimated: 'not_answered',
  blood_pressure_measured_high_number: '1',
  blood_pressure_measured_low_number: '1',
  blood_pressure_medication: '1',
  body_frame_size: 'not_answered',
  butter: 'not answered',
  caffeine: 'yes',
  charcoal_broiled: 'yes',
  chh_cough: 'not answered',
  chh_fever: 'not answered',
  chh_hands: 'not_answered',
  chh_interact: 'not answered',
  chh_sbreath: 'not answered',
  cholesterol_check: 'not_answered',
  cholesterol_level_estimated: 'not_answered',
  cholesterol_level_mml: '1',
  cholesterol_level: '1',
  cholesterol_medication: '1',
  colon_cancer_screening: '',
  commercial_driver: 'yes',
  cross_contamination: 'yes',
  daily_cigars: '2',
  daily_marajuana: '2',
  daily_pipes: '2',
  daily_shisha: '2',
  desserts: 'not answered',
  diabetes_status: 'yes',
  difficulties_piling_up: '',
  distracted_driving: 'yes',
  drinking_and_driving: '23',
  driving_speed: 'do not drive',
  education: '',
  fast_food: 'not answered',
  felt_confident: '',
  filling_forms: '',
  fish: 'yes',
  fruit: 'not answered',
  fruits_and_vegetables: 'yes',
  GADa: '',
  GADb: '',
  GADc: '',
  GADd: '',
  GADe: '',
  GADf: '',
  GADg: '',
  gainful_employment: '',
  going_your_way: '',
  gross_weight: 'yes',
  hb1ac_check: '',
  hdl_cholesterol_estimated: 'not_answered',
  hdl_cholesterol_mml: '4',
  hdl_cholesterol: '4',
  health_information_interest: '',
  heart_attack: 'yes',
  heart_disease: 'yes',
  height_cm: '2',
  height_feet: '1',
  height_inches: '2',
  height: '',
  helmet_usage: '',
  high_cholesterol_food: 'yes',
  hispanic_origin: '',
  home_safety: '',
  household_income: '',
  hysterectomy: '',
  insurance_coverage: '',
  junk_food: 'not answered',
  last_mammogram: '',
  marital_status: '',
  misfortune: '',
  overall_health: '',
  pap_smear_test: '',
  PHQa: '',
  PHQb: '',
  PHQc: '',
  PHQd: '',
  PHQe: '',
  PHQf: '',
  PHQg: '',
  PHQh: '',
  PHQi: '',
  protein: 'not answered',
  race: '',
  readiness_to_eat_healthier: '',
  readiness_to_exercise_more: '',
  readiness_to_quit_smoking: '',
  readiness_to_reduce_alcohol_usage: '',
  resting_heart_rate: '',
  road_rage: 'yes',
  safety_belt_usage: '4',
  save_key: '',
  sex: 'not_answered',
  sleep1: 'not answered',
  sleep2: 'not answered',
  sleep3: 'not answered',
  sleep4: 'not answered',
  smokeless_tobacco: '3',
  smoking: 'never_smoked',
  soft_drinks: 'not answered',
  stage: '',
  state_of_residence: '',
  still_smoke: '1',
  stroke: 'yes',
  sugar_beverage: 'yes',
  travel_by_automobile_km: '22',
  travel_by_automobile: '22',
  travel_by_motorcycle_km: '22',
  travel_by_motorcycle: '22',
  triglycerides: '4',
  type_of_license: 'a',
  typical_travel_method: 'not_answered',
  unable_to_control: '',
  used_to_smoke_cigarettes_day: '1',
  used_to_smoke_cigars_day: '1',
  used_to_smoke_pipes_day: '1',
  vaping_freq: '1-2 days',
  vaping: 'yes',
  vegetables: 'not answered',
  weekly_alcohol_beer: '40',
  weekly_alcohol_mixed_drinks: '54',
  weekly_alcohol_wine_coolers: '45',
  weekly_alcohol_wine: '90',
  weekly_physical_activity: '',
  weight_kg: '2',
  weight: '1',
  years_as_driver: '4',
  years_since_quitting_months: '4',
  years_since_quitting_years: '4',
}